DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
	`email` VARCHAR(32) NOT NULL,
	`password` VARCHAR(64) NOT NULL,
	`familyname` VARCHAR(64) NOT NULL,
	`class` VARCHAR(64) NOT NULL,
	`company` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`email`)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


DROP TABLE IF EXISTS `sapyo`;
CREATE TABLE `sapyo` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(32) NOT NULL,
	`submittime` DATETIME NOT NULL,
	PRIMARY KEY(`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


DROP TABLE IF EXISTS `contents`;
CREATE TABLE `contents` (
	`id` INTEGER NOT NULL,
	`contents` TEXT NOT NULL,
	`likes` INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;
